version: '3'

services: 
  db:
   image: postgres:14.3
   restart: always
   ports:
    - 5435:5432 # Connect ports
   environment: # Takes vars from .env file
     POSTGRES_PASSWORD: ${DB_PASSWORD}
     POSTGRES_DB: ${DB_NAME}
   container_name: api-etc-db
   volumes:
     - ./postgres:/var/lib/postgresql/data
  